platform :ios, '13.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterContainerDemo' do
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

  target 'FlutterContainerDemoTests' do
    inherit! :search_paths
  end

  target 'FlutterContainerDemoUITests' do
  end
end

post_install do |installer|
  flutter_post_install(installer)
end
